from __future__ import annotations

from typing import Any

from profiler.data_dictionary import build_data_dictionary


def _safe_markdown_value(value: object) -> str:
	if value is None:
		return ""
	text = str(value).replace("\n", " ").replace("\r", " ")
	return text.replace("|", "\\|")


def _format_sample_values(value: object) -> str:
	if isinstance(value, list):
		if not value:
			return ""
		return ", ".join(str(item) for item in value)
	if value is None:
		return ""
	return str(value)


def _format_percent_value(value: object) -> str:
	if value is None:
		return ""
	text = str(value).strip()
	if text.endswith("%"):
		text = text[:-1].rstrip()
	return text


def _format_percent_with_suffix(value: object) -> str:
	text = _format_percent_value(value)
	if not text:
		return ""
	return f"{text}%"


def build_markdown_report(
	profile: dict[str, Any],
	quality_checks: dict[str, Any],
	file_name: str,
	file_type: str,
	selected_sheet: str | None = None,
) -> str:
	lines: list[str] = []

	lines.append("# Blackmoor Data Profile Report")
	lines.append("")
	lines.append("This report was generated by Blackmoor Data Profiler.")
	lines.append("")
	lines.append("## Report Contents")
	lines.append("")
	lines.append("- Dataset Overview")
	lines.append("- Column Profile")
	lines.append("- Data Dictionary")
	lines.append("- Data Quality Summary")
	lines.append("- Data Quality Findings")
	lines.append("")
	lines.append("## Dataset Overview")
	lines.append("")
	lines.append(f"- File name: {_safe_markdown_value(file_name)}")
	lines.append(f"- File type: {_safe_markdown_value(file_type)}")
	if selected_sheet is not None:
		lines.append(f"- Selected sheet: {_safe_markdown_value(selected_sheet)}")
	lines.append(f"- Row count: {_safe_markdown_value(profile.get('row_count'))}")
	lines.append(f"- Column count: {_safe_markdown_value(profile.get('column_count'))}")
	lines.append("")

	lines.append("## Column Profile")
	lines.append("")
	lines.append("| Column | Inferred Type | Missing Count | Missing % | Distinct Count | Sample Values |")
	lines.append("| --- | --- | --- | --- | --- | --- |")
	for column in profile.get("columns", []):
		sample_values = _format_sample_values(column.get("sample_values"))
		missing_percent = _format_percent_with_suffix(column.get("missing_percent"))
		lines.append(
			"| "
			+ " | ".join(
				[
					_safe_markdown_value(column.get("column_name")),
					_safe_markdown_value(column.get("inferred_dtype")),
					_safe_markdown_value(column.get("missing_count")),
					_safe_markdown_value(missing_percent),
					_safe_markdown_value(column.get("distinct_count")),
					_safe_markdown_value(sample_values),
				]
			)
			+ " |"
		)
	lines.append("")

	lines.append("## Data Dictionary")
	lines.append("")
	lines.append("| Column | Inferred Type | Suggested Description | Missing % | Distinct Count | Sample Values |")
	lines.append("| --- | --- | --- | --- | --- | --- |")
	for row in build_data_dictionary(profile):
		sample_values = _format_sample_values(row.get("sample_values"))
		missing_percent = _format_percent_with_suffix(row.get("missing_percent"))
		lines.append(
			"| "
			+ " | ".join(
				[
					_safe_markdown_value(row.get("column_name")),
					_safe_markdown_value(row.get("inferred_dtype")),
					_safe_markdown_value(row.get("suggested_description")),
					_safe_markdown_value(missing_percent),
					_safe_markdown_value(row.get("distinct_count")),
					_safe_markdown_value(sample_values),
				]
			)
			+ " |"
		)
	lines.append("")

	lines.append("## Data Quality Summary")
	lines.append("")
	lines.append(
		f"- Duplicate row count: {_safe_markdown_value(quality_checks.get('duplicate_row_count'))}"
	)
	duplicate_row_percent = _format_percent_with_suffix(quality_checks.get("duplicate_row_percent"))
	lines.append(f"- Duplicate row percent: {_safe_markdown_value(duplicate_row_percent)}")
	lines.append("")

	lines.append("## Data Quality Findings")
	lines.append("")
	lines.append("Findings are heuristic first-pass indicators and may require human review.")
	lines.append("")
	findings = quality_checks.get("findings", [])
	if findings:
		lines.append("| Check | Severity | Column | Message |")
		lines.append("| --- | --- | --- | --- |")
		for finding in findings:
			lines.append(
				"| "
				+ " | ".join(
					[
						_safe_markdown_value(finding.get("check_name")),
						_safe_markdown_value(finding.get("severity")),
						_safe_markdown_value(finding.get("column_name")),
						_safe_markdown_value(finding.get("message")),
					]
				)
				+ " |"
			)
	else:
		lines.append("No data quality findings for the current checks.")

	return "\n".join(lines)
