from profiler.report_builder import build_markdown_report


def _sample_profile() -> dict:
	return {
		"row_count": 3,
		"column_count": 2,
		"columns": [
			{
				"column_name": "name",
				"inferred_dtype": "object",
				"missing_count": 0,
				"missing_percent": 0.0,
				"distinct_count": 3,
				"sample_values": ["Alice", "Bob"],
			},
			{
				"column_name": "score",
				"inferred_dtype": "int64",
				"missing_count": 1,
				"missing_percent": 33.33,
				"distinct_count": 2,
				"sample_values": [],
			},
		],
	}


def _sample_quality_checks() -> dict:
	return {
		"duplicate_row_count": 1,
		"duplicate_row_percent": 33.33,
		"findings": [
			{
				"check_name": "Blank-Heavy Column",
				"severity": "warning",
				"column_name": "notes",
				"message": "Column has 66.67% missing values.",
			}
		],
	}


def test_build_markdown_report_includes_title_and_dataset_overview():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "# Blackmoor Data Profile Report" in report
	assert "This report was generated by Blackmoor Data Profiler." in report
	assert "## Report Contents" in report
	assert "- Dataset Overview" in report
	assert "- Data Quality Findings" in report
	assert "## Dataset Overview" in report
	assert "- File name: customer_sample.csv" in report
	assert "- File type: CSV" in report
	assert "- Row count: 3" in report
	assert "- Column count: 2" in report


def test_build_markdown_report_includes_report_contents_section():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "## Report Contents" in report
	assert "- Column Profile" in report
	assert "- Data Dictionary" in report
	assert "- Data Quality Summary" in report
	assert "- Data Quality Findings" in report


def test_build_markdown_report_includes_selected_sheet_when_provided():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="excel_smoke_test.xlsx",
		file_type="Excel",
		selected_sheet="Sheet1",
	)

	assert "- Selected sheet: Sheet1" in report


def test_build_markdown_report_includes_column_profile_table():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "## Column Profile" in report
	assert "| Column | Inferred Type | Missing Count | Missing % | Distinct Count | Sample Values |" in report
	assert "| name | object | 0 | 0.0% | 3 | Alice, Bob |" in report
	assert "| score | int64 | 1 | 33.33% | 2 |  |" in report


def test_build_markdown_report_includes_data_dictionary_table():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "## Data Dictionary" in report
	assert "| Column | Inferred Type | Suggested Description | Missing % | Distinct Count | Sample Values |" in report
	assert "TODO: Describe the business meaning of this field." in report
	assert "| name | object | TODO: Describe the business meaning of this field. | 0.0% | 3 | Alice, Bob |" in report


def test_build_markdown_report_formats_duplicate_row_percent_cleanly():
	quality_checks = {
		"duplicate_row_count": 1,
		"duplicate_row_percent": "33.33%",
		"findings": [],
	}

	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=quality_checks,
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "- Duplicate row percent: 33.33%" in report
	assert "33.33%%" not in report


def test_build_markdown_report_joins_sample_values():
	profile = _sample_profile()
	profile["columns"][0]["sample_values"] = ["red", "green", "blue"]

	report = build_markdown_report(
		profile=profile,
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "red, green, blue" in report


def test_build_markdown_report_includes_data_quality_findings_table():
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=_sample_quality_checks(),
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "## Data Quality Findings" in report
	assert "Findings are heuristic first-pass indicators and may require human review." in report
	assert "| Check | Severity | Column | Message |" in report
	assert "| Blank-Heavy Column | warning | notes | Column has 66.67% missing values. |" in report


def test_build_markdown_report_handles_no_findings_message():
	quality_checks = {
		"duplicate_row_count": 0,
		"duplicate_row_percent": 0.0,
		"findings": [],
	}
	report = build_markdown_report(
		profile=_sample_profile(),
		quality_checks=quality_checks,
		file_name="customer_sample.csv",
		file_type="CSV",
	)

	assert "No data quality findings for the current checks." in report


def test_build_markdown_report_safely_handles_pipe_characters():
	profile = {
		"row_count": 1,
		"column_count": 1,
		"columns": [
			{
				"column_name": "name|with|pipe",
				"inferred_dtype": "object",
				"missing_count": 0,
				"missing_percent": 0.0,
				"distinct_count": 1,
				"sample_values": ["A|B"],
			}
		],
	}
	quality_checks = {
		"duplicate_row_count": 0,
		"duplicate_row_percent": 0.0,
		"findings": [
			{
				"check_name": "Possible Date Column",
				"severity": "info",
				"column_name": "date|col",
				"message": "Contains A|B patterns",
			}
		],
	}

	report = build_markdown_report(
		profile=profile,
		quality_checks=quality_checks,
		file_name="pipe|file.csv",
		file_type="CSV",
	)

	assert "pipe\\|file.csv" in report
	assert "name\\|with\\|pipe" in report
	assert "A\\|B" in report
	assert "date\\|col" in report
	assert "Contains A\\|B patterns" in report
	assert "| name\\|with\\|pipe | object | TODO: Describe the business meaning of this field. | 0.0% | 1 | A\\|B |" in report
